apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teflogpvc
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
 
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tefdatapvc
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 60Gi
