spring:
  kafka:
#    security:
#      protocol: "SSL"
    bootstrap-servers: 192.168.0.3:9092
    ssl:
      trust-store-location: file:/user/share/spring-boot-kafka-batch-consumer/client-certs/kafka.client.truststore.jks
      trust-store-password: keypass1
    consumer:
      group-id: Group-BC-TEST-ENV
      max-poll-records: 1000
      fetch-max-wait: 35000
      fetch-min-size: 3145728
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        max.partition.fetch.bytes: 13631488
        request.timeout.ms: 70000
        allow.auto.create.topics: false
        partition.assignment.strategy: org.apache.kafka.clients.consumer.RoundRobinAssignor
        fetch.max.bytes: 62914560
        spring.json.value.default.type: com.muru.kafka.consumer.demo.model.AlarmMessage
    listener:
      type: batch
      concurrency: 4
consumer:
  topic-names: AlarmSync1,AlarmSync2,AlarmSync3,AlarmSync4
  storage-path: /user/share/data
