package com.muru.kafka.consumer.demo;

import lombok.Data;

@Data
public class TestMessage {
    private String NetcoolEventAction; //5-10
    private String Identifier; //120
    private String Node; //20
    private String NodeAlias; //12
    private String Manager; //20
    private String Agent; //30
    private String AlertGroup; //15
    private String AlertKey; //50
    private int Severity; //1,
    private String Summary; //50
    private String StateChange; //20
    private String FirstOccurrence; //2021-11-29 12:45:13
    private String LastOccurrence; //2021-12-15 12:27:20
    private String InternalLast; //2021-12-15T12:27:28
    private int Poll;   //1
    private int Type;   //1
    private int Tally;  //4
    private int ClassA;  //6
    private int Grade;  //1
    private String Location; //10
    private int OwnerUID;   //5
    private int OwnerGID;   //1
    private int Acknowledged;   //1
    private int Flash;   //1
    private String EventId; //60
    private int ExpireTime;   //1
    private int ProcessReq;   //1
    private int SuppressEscl;   //2
    private String Customer;    //10
    private int PhysicalSlot;   //1
    private int PhysicalPort;   //1
    private int TaskList;   //1
    private String NmosSerial;  //5
    private int NmosObjInst;    //1
    private int NmosCauseType;  //1
    private String NmosDomainName;  //5
    private int NmosEntityId;   //1
    private int NmosManagedStatus;  //1
    private String NmosEventMap;    //10
    private String LocalNodeAlias;  //10
    private String LocalPriObj; //1
    private String LocalSecObj; //1
    private String LocalRootObj;    //1
    private int X733EventType;  //3
    private int X733ProbableCause;  //1
    private String X733SpecificProb;    //1
    private String X733CorrNotif;   //1
    private String URL; //15
    private String ExtendedAttr;    //15
    private int OldRow; //1
    private int ProbeSubSecondId;   //3
    private String BSM_Identity;    //1
    private String CollectionFirst; //1970-01-01T01:00:00
    private String AggregationFirst;  //2021-11-29T12:45:17
    private String AcknowledgeUID;  //3
    private int ToggleCount;    //1
    private int ToggleDelay;    //1
    private int EscalateFlag;    //1
    private String Family;  //1
    private String OnCall;  //1
    private String Ticket;  //15
    private int OldSeverity;    //1
    private String OldOccurrence;   //2021-11-29T12:45:13
    private int DeduplicationOrder;    //1
    private String CurrentSince;    //2021-11-29 12:45:13
    private String Site;   //10
    private String ParentElement;  //1
    private String Department;  //1
    private String IncidentID;  //1
    private int DevicePrio;    //1
    private String OperatorNote;   //50
    private int HighFlappingEndCount;    //1
    private String HighFlappingEndTime; //1970-01-01T01:00:00
    private int HighFlappingCount;    //1
    private int HighFlappingWindow;    //1
    private int LowFlappingEndCount;    //1
    private String LowFlappingEndTime;  //1970-01-01T01:00:00
    private int LowFlappingCount;    //1
    private int LowFlappingWindow;    //1
    private String WatchList;  //1
    private int TicketAction;   //3
    private String DiagInfo;   //1
    private String AlertKeyAlias;   //50
    private int EMSAlarmId;    //1
    private String XinY;  //1
    private String Info1;  //1
    private String Info2;  //1
    private int CallOut;    //1
    private int ServiceImpact;    //1
    private int ServicePrio;    //1
    private String Lon;  //1
    private String Lat;  //1
    private int ManagedFlag;   //2
    private String UTSAOT;  //1
    private int RCACauseType;    //1
    private String RCAEventType;  //1
    private String RCAIdentifier;  //1
    private int RCAOrgSeverity;    //1
    private String RCAProblemText;  //1
    private String RCAStateChange;  //2021-11-29T14:35:42
    private String RemoteNodeAlias;  //1
    private String RemotePriObj;  //1
    private String RemoteRootObj;  //1
    private String RemoteSecObj;  //1
    private String Service;  //1
    private String SEServiceName;  //1
    private String SEProblemText;  //1
    private int SEServiceType;    //1
    private int SEState;    //1
    private int Layer;    //1
    private String ClusterName;  //1
    private int ClusterSize;    //1
    private String MonitoringOptions;  //1
    private String UseType;  //1
    private String UTSTime1;    //2021-11-29T14:35:42
    private int RCAOldSeverity;    //1
    private int Parked;    //1
    private String FrontOffice;   //3
    private int Region;    //1
    private String AlarmHelp;  //1
    private String OIDKey;   //90
    private int OIDVisible;    //1
    private int ClassVisible;    //1
    private int NodeVisible;    //1
    private int NodeValue;    //1
    private String ParentIdentifier;  //1
    private String IBMExtractedType;  //1
    private int IBMProcessingStage;    //1
    private String ServerName;   //7
    private int ServerSerial;   //10
    private String pk;   //50
    private String pk_node;   //35
    private String pk_date;   //35
    private String Domain;  //1
    private String Alarm_Identifier;   //20
    private String Topic;   //10
    private String Use_Case;  //1
    private String Use_Case_Group;  //1
    private String delete_event;    //4,5
    private String daaip_correlation_id;  //1
    private String Alarm_Received_Time;//2021-12-15 12:28:06

}