jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: myappsecret
spring:
  kafka:
    security:
      protocol: "SSL"
    bootstrap-servers: KAFKA1-S1:9093,KAFKA2-S3:9093,KAFKA3-S4:9093
    ssl:
      trust-store-location: file:/data/workspace/tef-alarm-consumer/config/kafka.client.truststore.jks
      trust-store-password: ENC(mavEo6MBO4aHuCh8vw4Ob23GJGqAmaT6)
    consumer:
      group-id: APP_CONSUMER-GROUP
      max-poll-records: 1000
      fetch-max-wait: 35000
      fetch-min-size: 3145728
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        max.partition.fetch.bytes: 13631488
        request.timeout.ms: 70000
        allow.auto.create.topics: false
        partition.assignment.strategy: org.apache.kafka.clients.consumer.RoundRobinAssignor
        fetch.max.bytes: 62914560
        spring.json.value.default.type: com.myapp.tef.alarm.consumer.model.AlarmMessage
    listener:
      type: batch
      concurrency: 4
consumer:
  topic-names: AlarmSync1,AlarmSync2,AlarmSync3,AlarmSync4
  storage-path: /data/workspace/tef-alarm-consumer/nasmount
