apiVersion: v1
kind: PersistentVolume
metadata:
  name: teflogpv
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteMany
  nfs: 
    path: /srv/nfs/kubedata/teflogs/
    server: 172.31.16.223

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teflogpvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: tefdatapv
spec:
  capacity:
    storage: 60Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /srv/nfs/kubedata/tefnasmount/
    server: 172.31.16.223

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tefdatapvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 60Gi
